[package]
name = "hello-rs"
version = "1.8.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
openweathermap = "0.2"
substring = "1.4"
subprocess = "0.2"
chrono = "0.4"
unicode-segmentation = "1.9"