[package]
edition = "2021"
name = "hello-rs"
version = "1.9.0"

[dependencies]
argparse = "0.2.2"
chrono = "0.4"
openweathermap = "0.2"
serde_json = "1.0"
subprocess = "0.2"
substring = "1.4"
unicode-segmentation = "1.9"
systemstat = "0.1.10"