[package]
name = "hello-rs"
version = "1.6.1"
edition = "2021"

[dependencies]
serde_json = "1.0"
openweathermap = "0.2.4"
substring = "1.4.5"
subprocess = "0.1.12"
chrono = "0.4"
unicode-segmentation = "1.9.0"
nix = "0.23.1"