[package]
edition = "2021"
name = "hello-rs"
version = "2.0.0"

[dependencies]
argparse = "0.2"
chrono = "0.4"
openweathermap = "0.2"
serde_json = "1.0"
subprocess = "0.2"
substring = "1.4"
unicode-segmentation = "1.9"
systemstat = "0.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
once_cell = "1.10"